[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_donation = "2qqDQ8RadpzattcT4mAcxuzrLjrvsmz3NXDqf72pmyYR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/andrey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
